apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbitmq-svc
  namespace: disk # 所在的命名空间
spec:
  ports:
  - name: http # service 端口配置的名称
    protocol: TCP # 端口绑定的协议，支持 TCP、UDP、SCTP，默认为 TCP
    port: 5672 # service 自己的端口
    targetPort: 5672 # 目标 pod 的端口
  - name: http-management # service 端口配置的名称
    protocol: TCP # 端口绑定的协议，支持 TCP、UDP、SCTP，默认为 TCP
    port: 15672 # service 自己的端口
    targetPort: 15672 # 目标 pod 的端口
  - name: http-management2 # service 端口配置的名称
    protocol: TCP # 端口绑定的协议，支持 TCP、UDP、SCTP，默认为 TCP
    port: 25672 # service 自己的端口
    targetPort: 25672 # 目标 pod 的端口
  selector: # 选中当前 service 匹配哪些 pod，对哪些 pod 的东西流量进行代理
    app: rabbitmq-deploy
  type: NodePort
